Add router transition view spy for double router.contact() assertion
This codes around a thrown error when running tests:
    TypeError: 'undefined' is not an object (evaluating 'this.model.get('active_view').el.setAttribute')
Although it would be better to find why this error occurs, for the purposes of this assertion it's not required that the actual transition occur